/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsIndexRouteImport } from './routes/treatments.index'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsIndexRoute = TreatmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TreatmentsRoute,
} as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreatmentsRoute,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/facilities': typeof FacilitiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/facilities': typeof FacilitiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments': typeof TreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/facilities': typeof FacilitiesRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap': typeof SitemapRoute
  '/terms': typeof TermsRoute
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blogs/$slug': typeof BlogsSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/': typeof TreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/cookies'
    | '/facilities'
    | '/privacy'
    | '/sitemap'
    | '/terms'
    | '/treatments'
    | '/blogs/$slug'
    | '/treatments/$slug'
    | '/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/cookies'
    | '/facilities'
    | '/privacy'
    | '/sitemap'
    | '/terms'
    | '/blogs/$slug'
    | '/treatments/$slug'
    | '/treatments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/cookies'
    | '/facilities'
    | '/privacy'
    | '/sitemap'
    | '/terms'
    | '/treatments'
    | '/blogs/$slug'
    | '/treatments/$slug'
    | '/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FacilitiesRoute: typeof FacilitiesRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapRoute: typeof SitemapRoute
  TermsRoute: typeof TermsRoute
  TreatmentsRoute: typeof TreatmentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/': {
      id: '/treatments/'
      path: '/'
      fullPath: '/treatments/'
      preLoaderRoute: typeof TreatmentsIndexRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

interface TreatmentsRouteChildren {
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  TreatmentsIndexRoute: typeof TreatmentsIndexRoute
}

const TreatmentsRouteChildren: TreatmentsRouteChildren = {
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  TreatmentsIndexRoute: TreatmentsIndexRoute,
}

const TreatmentsRouteWithChildren = TreatmentsRoute._addFileChildren(
  TreatmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FacilitiesRoute: FacilitiesRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapRoute: SitemapRoute,
  TermsRoute: TermsRoute,
  TreatmentsRoute: TreatmentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
